name: Publish Docker Image

on:
  push:
    branches:
      - master  # Si attiva quando viene fatto un push sulla branch 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Esegue il checkout del codice

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Cache dipendenze Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-

    #- name: Analisi del codice con SonarQube
    #  run: mvn sonar:sonar -Dsonar.organization=riccardo2001 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    #- name: Pubblica su GitHub Packages
    #  run: mvn deploy
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Build with Maven
      run: mvn clean install -DskipTests  # Esegui la build Maven (puoi includere i test, se necessario)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Imposta Docker Buildx per build multi-architettura

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Username di Docker Hub (salvato in Secrets)
        password: ${{ secrets.DOCKER_PASSWORD }}  # Password di Docker Hub (salvato in Secrets)

    - name: Build Docker image
      run: |
        docker build -t riklupo2001/jdbc2rest:latest .  # Costruisce l'immagine Docker

    - name: Push Docker image
      run: |
        docker push riklupo2001/jdbc2rest:latest  # Pusha l'immagine nel Docker registry
    
    - name: Install FortiClient dependencies
      run: |
        # Aggiungi la chiave GPG
        curl -fsSL https://repo.fortinet.com/repo/6.4/ubuntu/DEB-GPG-KEY | sudo tee /etc/apt/trusted.gpg.d/fortinet.asc

        # Aggiungi il repository FortiClient
        echo "deb https://repo.fortinet.com/repo/6.4/ubuntu/ stable main" | sudo tee /etc/apt/sources.list.d/fortinet.list

        # Aggiorna il repository e installa FortiClient
        sudo apt-get update
        sudo apt-get install -y forticlient

    - name: Connect to VPN using FortiClient
      run: |
        # Connetti alla VPN usando le credenziali
        sudo forticlient vpn -c -h your-vpn-server-address -u ${{ secrets.VPN_USERNAME }} -p ${{ secrets.VPN_PASSWORD }}

    - name: Wait for VPN to connect
      run: sleep 10 # Attendere la connessione VPN

    #- name: Deploy su server remoto
    #  run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER_SERVER }} "docker pull riklupo2001/jdbc2rest:latest && docker-compose up -d"

