name: Publish Docker Image

on:
  push:
    branches:
      - master  # Si attiva quando viene fatto un push sulla branch 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Esegue il checkout del codice

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        java-package: jdk
        architecture: x64
        distribution: 'adoptopenjdk'  # Aggiungi questo parametro
      # Imposta Java 17 (o la versione che utilizzi nel tuo progetto)

    - name: Build with Maven
      run: mvn clean install -DskipTests  # Esegui la build Maven (puoi includere i test, se necessario)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Imposta Docker Buildx per build multi-architettura

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Username di Docker Hub (salvato in Secrets)
        password: ${{ secrets.DOCKER_PASSWORD }}  # Password di Docker Hub (salvato in Secrets)

    - name: Build Docker image
      run: |
        docker build -t riccardo2001/jdbc2rest:latest .  # Costruisce l'immagine Docker

    - name: Push Docker image
      run: |
        docker push myusername/jdbc2rest:latest  # Pusha l'immagine nel Docker registry
